import assert from 'node:assert/strict';
import test from 'node:test';
import { MissionQueue } from './mission-queue.mjs';

test('claims by priority and capability',()=>{const q=new MissionQueue();q.enqueue({task:'low',priority:1,requiredCapabilities:['qa']});const high=q.enqueue({task:'high',priority:9,requiredCapabilities:['qa']});assert.equal(q.claim({id:'w1',capabilities:['qa']}).id,high.id);});
test('expired lease is retried then permanently failed',()=>{let now=0;const q=new MissionQueue({maxAttempts:2,leaseMs:10,now:()=>now});const m=q.enqueue({task:'synthetic defensive benchmark'});q.claim({id:'w1'});now=11;q.requeueExpired();assert.equal(q.get(m.id).status,'queued');q.claim({id:'w2'});now=22;q.requeueExpired();assert.equal(q.get(m.id).status,'failed');});
test('only owning worker can complete',()=>{const q=new MissionQueue();const m=q.enqueue({task:'benchmark'});q.claim({id:'owner'});assert.throws(()=>q.complete(m.id,'other'),/not owned/);assert.equal(q.complete(m.id,'owner').status,'completed');});
test('dependencies block claims until prerequisites complete',()=>{const q=new MissionQueue();const a=q.enqueue({task:'attempt',requiredCapabilities:['coder']});const b=q.enqueue({task:'review',requiredCapabilities:['qa'],dependsOn:[a.id]});assert.equal(q.stats().blocked,1);q.claim({id:'coder',capabilities:['coder']});q.complete(a.id,'coder');assert.equal(q.claim({id:'qa',capabilities:['qa']}).id,b.id);});
test('unknown dependency is rejected',()=>{const q=new MissionQueue();assert.throws(()=>q.enqueue({task:'bad',dependsOn:['missing']}),/dependency not found/);});
test('cancel releases running mission and rejects stale completion',()=>{const q=new MissionQueue();const m=q.enqueue({task:'long synthetic task'});q.claim({id:'w1'});assert.equal(q.cancel(m.id,'operator stop').status,'cancelled');assert.throws(()=>q.complete(m.id,'w1'),/cancelled/);});
test('failed dependency cancels downstream chain',()=>{const q=new MissionQueue({maxAttempts:1});const root=q.enqueue({task:'root'});const child=q.enqueue({task:'child',dependsOn:[root.id]});const grand=q.enqueue({task:'grandchild',dependsOn:[child.id]});q.claim({id:'w1'});q.fail(root.id,'w1','synthetic');assert.equal(q.get(child.id).status,'cancelled');assert.equal(q.get(grand.id).status,'cancelled');});
test('idempotency key returns original mission',()=>{const q=new MissionQueue();const a=q.enqueue({task:'once',idempotencyKey:'job-1'});const b=q.enqueue({task:'duplicate payload ignored',idempotencyKey:'job-1'});assert.equal(b.id,a.id);assert.equal(q.stats().total,1);});
test('snapshot preserves completed state and idempotency',()=>{const q=new MissionQueue();const m=q.enqueue({task:'once',idempotencyKey:'stable'});q.claim({id:'w'});q.complete(m.id,'w',{ok:true});const recovered=new MissionQueue({snapshot:q.snapshot()});assert.equal(recovered.get(m.id).status,'completed');assert.equal(recovered.enqueue({task:'retry',idempotencyKey:'stable'}).id,m.id);});
test('restart recovers in-flight lease without double ownership',()=>{let now=100;const q=new MissionQueue({maxAttempts:3,now:()=>now});const m=q.enqueue({task:'work'});q.claim({id:'old'});now=200;const recovered=new MissionQueue({maxAttempts:3,now:()=>now,snapshot:q.snapshot()});assert.equal(recovered.get(m.id).status,'queued');assert.equal(recovered.get(m.id).workerId,null);assert.equal(recovered.claim({id:'new'}).attempts,2);assert.throws(()=>recovered.complete(m.id,'old'),/not owned/);});
test('restart terminalizes exhausted in-flight mission and propagates dependency failure',()=>{const q=new MissionQueue({maxAttempts:1});const root=q.enqueue({task:'root'});const child=q.enqueue({task:'child',dependsOn:[root.id]});q.claim({id:'old'});const recovered=new MissionQueue({maxAttempts:1,snapshot:q.snapshot()});assert.equal(recovered.get(root.id).status,'failed');assert.equal(recovered.get(child.id).status,'cancelled');});
