import test from 'node:test';
import assert from 'node:assert/strict';
import { buildReadonlyQrexecPolicyQualification, verifyReadonlyQrexecPolicyQualification } from './qrexec-readonly-policy-qualification.mjs';
const SHA = '1234567890abcdef1234567890abcdef12345678';
const scenarios = { 'intended-service-allowed': { outcome: 'allowed', exitCode: 0 }, 'wrong-service-denied': { outcome: 'denied', exitCode: 1 }, 'wrong-identity-denied': { outcome: 'denied', exitCode: 2 }, 'auth-failure-denied': { outcome: 'denied', exitCode: 2 }, 'malformed-framing-denied': { outcome: 'denied', exitCode: 2 } };
const same = () => ({ missionStoreBefore:'mission:same', missionStoreAfter:'mission:same', requestJournalBefore:'journal:same', requestJournalAfter:'journal:same' });
function fixture(overrides={}) { return { gitSha:SHA, runtimeFingerprint:'node-v24|qubes-4.x', sourceQube:'worker', coordinatorQube:'coordinator', intendedService:'dig.QubesReadonlyProbe', scenarios:structuredClone(scenarios), attestationVerified:true, responseBounded:true, singleResponseFrame:true, mutationEvidence:same(), scenarioMutationEvidence:Object.fromEntries(Object.keys(scenarios).map(name=>[name,same()])), ...overrides }; }
test('builds schema v2 with scenario-local zero-mutation evidence',()=>{ const report=buildReadonlyQrexecPolicyQualification(fixture()); assert.equal(report.schemaVersion,2); assert.equal(report.readiness,'LAB READY'); assert.equal(verifyReadonlyQrexecPolicyQualification(report),true); });
test('wrong service must be denied',()=>{ const input=fixture(); input.scenarios['wrong-service-denied']={outcome:'allowed',exitCode:0}; assert.throws(()=>buildReadonlyQrexecPolicyQualification(input),/wrong-service-denied must be denied/); });
test('aggregate mutation fails closed',()=>{ const input=fixture({mutationEvidence:{...same(),missionStoreAfter:'mission:changed'}}); assert.throws(()=>buildReadonlyQrexecPolicyQualification(input),/mutationEvidence mutated MissionStore/); });
test('scenario-local mutation fails even if aggregate evidence is unchanged',()=>{ const input=fixture(); input.scenarioMutationEvidence['auth-failure-denied']={...same(),requestJournalAfter:'journal:temporary'}; assert.throws(()=>buildReadonlyQrexecPolicyQualification(input),/scenarioMutationEvidence\.auth-failure-denied mutated DurableRequestJournal/); });
test('attestation, byte bound, and single-frame evidence are mandatory',()=>{ assert.throws(()=>buildReadonlyQrexecPolicyQualification(fixture({attestationVerified:false})),/attestation/); assert.throws(()=>buildReadonlyQrexecPolicyQualification(fixture({responseBounded:false})),/byte bound/); assert.throws(()=>buildReadonlyQrexecPolicyQualification(fixture({singleResponseFrame:false})),/one response frame/); });
test('tampering invalidates evidence digest',()=>{ const report=buildReadonlyQrexecPolicyQualification(fixture()); assert.throws(()=>verifyReadonlyQrexecPolicyQualification({...report,sourceQube:'other'}),/digest mismatch/); });
