import assert from 'node:assert/strict';
import test from 'node:test';
import { evaluateAttestedMultiRunQualification } from './qubes-attested-multi-run-qualification.mjs';
const SHA='a'.repeat(40),NORMAL='dig.Coordinator',FAULT='dig.CoordinatorFault',KEY='dig-key-1';
const baseThresholds={expectedGitSha:SHA,expectedSourceQube:'worker',expectedTargetQube:'coordinator',expectedService:NORMAL,expectedFaultService:FAULT,expectedAttestationKeyId:KEY,nowMs:Date.parse('2026-08-18T10:00:02Z')};
const a=(service,requestId)=>({service,keyId:KEY,gitSha:SHA,...(requestId?{requestId}:{})});
const graph=(prefix='g1')=>({type:'mission_graph_instance',missionIds:[`${prefix}-planner`,`${prefix}-coder`,`${prefix}-qa`],dependencyEdges:[{from:`${prefix}-planner`,to:`${prefix}-coder`},{from:`${prefix}-coder`,to:`${prefix}-qa`}]});
function campaign(attestations=[],{runId='r1',second=0,mutationKey=null,missionGraph=null}={}){const requestIds=[...new Set(attestations.map(item=>item.requestId).filter(Boolean))],pad=String(second).padStart(2,'0');return[{type:'campaign_start',runId,transport:'qrexec',sourceQube:'worker',targetQube:'coordinator',service:NORMAL,gitSha:SHA,startedAt:`2026-08-18T10:00:${pad}Z`},...requestIds.map(requestId=>({type:'request_pending',requestId})),...attestations.map(item=>({type:'attestation_verified',...item})),...(missionGraph?[missionGraph]:[]),...(mutationKey?[{type:'mutation_committed',mutationKey}]:[]),...requestIds.map(requestId=>({type:'request_resolved',requestId})),{type:'campaign_end',runId,finishedAt:`2026-08-18T10:00:${String(second+1).padStart(2,'0')}Z`}];}
test('attested qualification fails closed without verified campaign and dual-service preflight evidence',()=>{const result=evaluateAttestedMultiRunQualification([campaign()],baseThresholds);assert.equal(result.ready,false);for(const failed of ['verifiedAttestationEvidencePresent','verifiedNormalServiceCampaignAttestationObserved','verifiedFaultServicePreflightAttestationObserved','allCampaignAttestationsBoundToObservedRequests','allCampaignAttestationsBoundToCompletedLifecycles','missionGraphEvidencePresent'])assert.ok(result.failedChecks.includes(failed),failed);});
test('fault service attestation is sourced from read-only preflight while normal campaign response is request-bound and resolved',()=>{const thresholds={...baseThresholds,preflightVerifiedAttestations:[a(NORMAL),a(FAULT)]};const result=evaluateAttestedMultiRunQualification([campaign([a(NORMAL,'req-1')],{mutationKey:'mutation-r1',missionGraph:graph('r1')})],thresholds);for(const check of ['verifiedNormalServiceCampaignAttestationObserved','verifiedNormalServicePreflightAttestationObserved','verifiedFaultServicePreflightAttestationObserved','onlyExpectedAttestationBindingsObserved','allCampaignAttestationsBoundToObservedRequests','allCampaignAttestationsBoundToCompletedLifecycles','requestIdsIndependentAcrossRuns','mutationIdentitiesIndependentAcrossRuns','missionGraphEvidencePresent','missionIdsIndependentAcrossRuns','missionGraphInstancesIndependentAcrossRuns'])assert.equal(result.checks[check],true,check);assert.equal(result.metrics.completedVerifiedRequestLifecycles,1);assert.equal(result.metrics.totalMissionGraphInstances,1);assert.equal(result.metrics.uniqueMissionIds,3);assert.equal(result.ready,false);});
test('collector rejects a verified response whose request lifecycle never started',()=>{const events=campaign([a(NORMAL,'req-1')]).filter(event=>event.type!=='request_pending');assert.throws(()=>evaluateAttestedMultiRunQualification([events],{...baseThresholds,preflightVerifiedAttestations:[a(NORMAL),a(FAULT)]}),/attestation_verified requires pending request/);});
test('attested qualification rejects verified evidence whose request never resolves',()=>{const events=campaign([a(NORMAL,'req-1')],{missionGraph:graph('r1')}).filter(event=>event.type!=='request_resolved');const result=evaluateAttestedMultiRunQualification([events],{...baseThresholds,preflightVerifiedAttestations:[a(NORMAL),a(FAULT)]});assert.equal(result.checks.allCampaignAttestationsBoundToCompletedLifecycles,false);assert.equal(result.metrics.completedVerifiedRequestLifecycles,0);assert.ok(result.failedChecks.includes('allCampaignAttestationsBoundToCompletedLifecycles'));});
test('attested qualification rejects request identity reuse across otherwise distinct runs',()=>{const thresholds={...baseThresholds,minRuns:2,preflightVerifiedAttestations:[a(NORMAL),a(FAULT)]};const result=evaluateAttestedMultiRunQualification([campaign([a(NORMAL,'shared-request')],{runId:'r1',second:0,missionGraph:graph('r1')}),campaign([a(NORMAL,'shared-request')],{runId:'r2',second:2,missionGraph:graph('r2')})],thresholds);assert.equal(result.checks.requestIdsIndependentAcrossRuns,false);assert.equal(result.metrics.crossRunRequestReuse,1);assert.ok(result.failedChecks.includes('requestIdsIndependentAcrossRuns'));});
test('attested qualification rejects committed mutation identity reuse across distinct runs',()=>{const thresholds={...baseThresholds,minRuns:2,preflightVerifiedAttestations:[a(NORMAL),a(FAULT)]};const result=evaluateAttestedMultiRunQualification([campaign([a(NORMAL,'request-r1')],{runId:'r1',second:0,mutationKey:'shared-mutation',missionGraph:graph('r1')}),campaign([a(NORMAL,'request-r2')],{runId:'r2',second:2,mutationKey:'shared-mutation',missionGraph:graph('r2')})],thresholds);assert.equal(result.checks.mutationIdentitiesIndependentAcrossRuns,false);assert.equal(result.metrics.crossRunMutationIdentityReuse,1);});
test('attested qualification rejects mission id and durable graph-instance reuse across runs',()=>{const thresholds={...baseThresholds,minRuns:2,preflightVerifiedAttestations:[a(NORMAL),a(FAULT)]},shared=graph('shared');const result=evaluateAttestedMultiRunQualification([campaign([a(NORMAL,'request-r1')],{runId:'r1',second:0,missionGraph:shared}),campaign([a(NORMAL,'request-r2')],{runId:'r2',second:2,missionGraph:structuredClone(shared)})],thresholds);assert.equal(result.checks.missionIdsIndependentAcrossRuns,false);assert.equal(result.checks.missionGraphInstancesIndependentAcrossRuns,false);assert.equal(result.metrics.crossRunMissionIdReuse,3);assert.equal(result.metrics.crossRunMissionGraphReuse,1);assert.ok(result.failedChecks.includes('missionIdsIndependentAcrossRuns'));assert.ok(result.failedChecks.includes('missionGraphInstancesIndependentAcrossRuns'));});
test('same logical DAG is allowed when durable mission instances are fresh',()=>{const thresholds={...baseThresholds,minRuns:2,preflightVerifiedAttestations:[a(NORMAL),a(FAULT)]};const result=evaluateAttestedMultiRunQualification([campaign([a(NORMAL,'request-r1')],{runId:'r1',second:0,missionGraph:graph('one')}),campaign([a(NORMAL,'request-r2')],{runId:'r2',second:2,missionGraph:graph('two')})],thresholds);assert.equal(result.checks.missionIdsIndependentAcrossRuns,true);assert.equal(result.checks.missionGraphInstancesIndependentAcrossRuns,true);assert.equal(result.metrics.uniqueMissionIds,6);assert.equal(result.metrics.crossRunMissionIdReuse,0);assert.equal(result.metrics.crossRunMissionGraphReuse,0);});
test('attested qualification rejects wrong key id, sha, service, and missing fault preflight coverage',()=>{for(const[name,preflight,campaignEvents,failed]of[['wrong key',[{service:NORMAL,keyId:'other',gitSha:SHA},a(FAULT)],[a(NORMAL,'req-1')],'onlyExpectedAttestationBindingsObserved'],['wrong sha',[{service:NORMAL,keyId:KEY,gitSha:'b'.repeat(40)},a(FAULT)],[a(NORMAL,'req-1')],'onlyExpectedAttestationBindingsObserved'],['third service',[a(NORMAL),a(FAULT),a('dig.Other')],[a(NORMAL,'req-1')],'onlyExpectedAttestationBindingsObserved'],['missing fault preflight',[a(NORMAL)],[a(NORMAL,'req-1')],'verifiedFaultServicePreflightAttestationObserved'],['missing campaign verification',[a(NORMAL),a(FAULT)],[],'verifiedNormalServiceCampaignAttestationObserved']]){const result=evaluateAttestedMultiRunQualification([campaign(campaignEvents,{missionGraph:graph('r1')})],{...baseThresholds,preflightVerifiedAttestations:preflight});assert.equal(result.ready,false,name);assert.ok(result.failedChecks.includes(failed),name);}});