import test from 'node:test';
import assert from 'node:assert/strict';
import { runQualificationPreflight, runQualificationPreflightFromEnv, validateQualificationPreflightEnvironment } from './qubes-qrexec-qualification-preflight.mjs';

const SECRET='s'.repeat(32), SHA='a'.repeat(40), KEY='dig-key-1', PUB='test-public-key', TOPOLOGY='two-worker-fused', DIGEST='b'.repeat(64);
const ENV={DIG_QREXEC_SOURCE:'dig-worker',DIG_QREXEC_TARGET:'dig-coordinator',DIG_QREXEC_SERVICE:'dig.Coordinator',DIG_QREXEC_FAULT_SERVICE:'dig.CoordinatorFault',DIG_GIT_SHA:SHA,DIG_QUBES_TOPOLOGY_ID:TOPOLOGY,DIG_CALIBRATION_EVIDENCE_DIGEST:DIGEST,DIG_TRANSPORT_SECRET:SECRET,DIG_RESPONSE_ATTESTATION_PUBLIC_KEY:PUB,DIG_RESPONSE_ATTESTATION_KEY_ID:KEY};
const verified=service=>({service,keyId:KEY,gitSha:SHA,topologyId:TOPOLOGY,calibrationEvidenceDigest:DIGEST});

test('validates fail-closed qualification environment including calibrated attestation binding',()=>{const config=validateQualificationPreflightEnvironment(ENV);assert.equal(config.topologyId,TOPOLOGY);assert.equal(config.calibrationEvidenceDigest,DIGEST);assert.throws(()=>validateQualificationPreflightEnvironment({...ENV,DIG_QREXEC_TARGET:'dig-worker'}),/distinct source and target/);assert.throws(()=>validateQualificationPreflightEnvironment({...ENV,DIG_QREXEC_FAULT_SERVICE:'dig.Coordinator'}),/distinct normal and fault/);assert.throws(()=>validateQualificationPreflightEnvironment({...ENV,DIG_GIT_SHA:'bad'}),/40-character hex SHA/);assert.throws(()=>validateQualificationPreflightEnvironment({...ENV,DIG_CALIBRATION_EVIDENCE_DIGEST:'BAD'}),/lowercase SHA-256/);const noTopology={...ENV};delete noTopology.DIG_QUBES_TOPOLOGY_ID;assert.throws(()=>validateQualificationPreflightEnvironment(noTopology),/DIG_QUBES_TOPOLOGY_ID/);});

test('authenticated stats probe requires verified calibrated coordinator attestation',async()=>{let seen;const result=await runQualificationPreflight({secret:SECRET,requestId:'preflight-1',issuedAt:1234,expectedService:'dig.Coordinator',expectedKeyId:KEY,expectedGitSha:SHA,expectedTopologyId:TOPOLOGY,expectedCalibrationEvidenceDigest:DIGEST,invoke:async envelope=>{seen=envelope;return{response:{ok:true,result:{queued:0}},durationMs:7,attestationVerified:verified('dig.Coordinator')}}});assert.equal(seen.requestId,'preflight-1');assert.equal(result.durationMs,7);assert.deepEqual(result.attestation,verified('dig.Coordinator'));});

test('preflight fails closed on wrong or legacy calibration attestation',async()=>{const base={secret:SECRET,expectedService:'dig.Coordinator',expectedKeyId:KEY,expectedGitSha:SHA,expectedTopologyId:TOPOLOGY,expectedCalibrationEvidenceDigest:DIGEST};await assert.rejects(()=>runQualificationPreflight({...base,invoke:async()=>({response:{ok:true,result:{}},durationMs:1,attestationVerified:{...verified('dig.Coordinator'),topologyId:'other'}})}),/topology mismatch/);await assert.rejects(()=>runQualificationPreflight({...base,invoke:async()=>({response:{ok:true,result:{}},durationMs:1,attestationVerified:{service:'dig.Coordinator',keyId:KEY,gitSha:SHA}})}),/topology mismatch/);await assert.rejects(()=>runQualificationPreflight({...base,invoke:async()=>({response:{ok:true,result:{}},durationMs:1,attestationVerified:{...verified('dig.Coordinator'),calibrationEvidenceDigest:'c'.repeat(64)}})}),/calibration digest mismatch/);});

test('environment preflight probes both services under the same calibrated binding',async()=>{const result=await runQualificationPreflightFromEnv({env:ENV,invoke:async()=>({response:{ok:true,result:{queued:1}},durationMs:5,attestationVerified:verified('dig.Coordinator')}),faultInvoke:async()=>({response:{ok:true,result:{queued:1}},durationMs:6,attestationVerified:verified('dig.CoordinatorFault')})});assert.equal(result.durationMs,11);assert.equal(result.topologyId,TOPOLOGY);assert.equal(result.calibrationEvidenceDigest,DIGEST);assert.deepEqual(result.verifiedAttestations,[verified('dig.Coordinator'),verified('dig.CoordinatorFault')]);});

test('environment preflight fails before campaigns when fault service lacks verified attestation',async()=>{await assert.rejects(()=>runQualificationPreflightFromEnv({env:ENV,invoke:async()=>({response:{ok:true,result:{}},durationMs:1,attestationVerified:verified('dig.Coordinator')}),faultInvoke:async()=>({response:{ok:true,result:{}},durationMs:1})}),/requires verified coordinator response attestation/);});
